name: Crowdin Download Action
description: Downloads translations from Crowdin and merges into the specified Git branch
author: "eXo Platform"
inputs:
  PROJECT_VERSION:
    description: Project version
    required: true
  PROJECT_BRANCH:
    description: Project git branch
    required: true
  CROWDIN_BRANCH:
    description: Crowdin branch name
    default: ""
    required: false
  CROWDIN_LANGUAGES_ARG:
    description: Crowdin args for used languages
    default: "-l ar -l aro -l az -l ca -l ceb -l co -l cs -l de -l el -l en -l es-ES -l eu -l fa -l fi -l fil -l fr -l hi -l hu -l id -l it -l ja -l ko -l lt -l ms -l nl -l no -l pcm -l pl -l pt-BR -l pt-PT -l ro -l ru -l sk -l sl -l sq -l sv-SE -l th -l tl -l tr -l uk -l ur-IN -l vi -l zh-CN -l zh-TW"
    required: false
  YML_CROWDIN_LANGUAGES_ARG:
    description: Crowdin language env var for crowdin.yml file
    default: '"_en!": "","ar_SA": "ar","ar_OM": "aro","az_AZ": "az","ca_ES": "ca","ceb_PH": "ceb", "co_FR": "co","cs_CZ": "cs","de_DE": "de","el_GR": "el","en_US": "en","es_ES": "es_ES","eu_ES": "eu","fa_IR": "fa", "fi_FI": "fi","fil_PH": "fil","fr_FR": "fr","hi_IN": "hi","hu_HU": "hu","id_ID": "id","it_IT": "it","ja_JP": "ja", "kab_KAB": "kab","ko_KR": "ko","lt_LT": "lt","ms_MY": "ms","nl_NL": "nl","no_NO": "no","pcm_NG": "pcm","pl_PL": "pl", "pt_BR": "pt_BR","pt_PT": "pt_PT","ro_RO": "ro","ru_RU": "ru","sk_SK": "sk","sl_SI": "sl","sq_AL": "sq", "sv_SE": "sv_SE","th_TH": "th","tl_PH": "tl","tr_TR": "tr","uk_UA": "uk","ur_IN": "ur_IN","vi_VN": "vi", "zh_CN": "zh_CN","zh_TW": "zh_TW",'
    required: false
  CROWDIN_PROJECT_ID:
    description: Crowdin project ID
    required: true
  CROWDIN_PERSONAL_TOKEN:
    description: Crowdin personal access token
    required: true
  CROWDIN_GITHUB_TOKEN:
    description: GitHub token for checkout and Crowdin
    required: true
  CROWDIN_COMMITTER_NAME:
    description: Git Committer name
    required: true
  CROWDIN_COMMITTER_EMAIL:
    description: Git Committer email
    required: true
  CROWDIN_COMMIT_GPG_PRIVATE_KEY:
    description: Crowdin Commit GPG private key
    default: ""
    required: false
  CROWDIN_COMMIT_GPG_PASSPHRASE:
    description: Crowdin Commit GPG passphrase
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        token: ${{ inputs.CROWDIN_GITHUB_TOKEN }}
        ref: ${{ inputs.PROJECT_BRANCH }}

    - name: Reset translation branch
      shell: bash
      run: |
        git push origin origin/${{ inputs.PROJECT_BRANCH }}:refs/heads/integration/${{ inputs.PROJECT_VERSION }}-translation -f

    - name: Setup language replacement to crowdin.yml file
      shell: bash
      run: |
        sed -i "s/YML_CROWDIN_LANGUAGES_ARG/${{ inputs.YML_CROWDIN_LANGUAGES_ARG }}/g" crowdin.yml

    - name: Crowdin download
      uses: crowdin/github-action@v2
      with:
        upload_sources: false
        upload_translations: false
        download_translations: true
        crowdin_branch_name: ${{ inputs.CROWDIN_BRANCH }}
        localization_branch_name: integration/${{ inputs.PROJECT_VERSION }}-translation
        create_pull_request: false
        skip_ref_checkout: true
        download_translations_args: ${{ inputs.CROWDIN_LANGUAGES_ARG }}
      env:
        CROWDIN_PROJECT_ID: ${{ inputs.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ inputs.CROWDIN_PERSONAL_TOKEN }}
        GITHUB_TOKEN: ${{ inputs.CROWDIN_GITHUB_TOKEN }}

    - name: Import GPG key for commit signing
      if: ${{ inputs.CROWDIN_COMMIT_GPG_PRIVATE_KEY != '' }}
      uses: crazy-max/ghaction-import-gpg@v7
      with:
        gpg_private_key: ${{ inputs.CROWDIN_COMMIT_GPG_PRIVATE_KEY }}
        passphrase: ${{ inputs.CROWDIN_COMMIT_GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Merge translation to ${{ inputs.PROJECT_BRANCH }}
      shell: bash
      run: |
        if [ -z "${{ inputs.CROWDIN_COMMITTER_EMAIL }}"] || [ -z "${{ inputs.CROWDIN_COMMITTER_NAME }}" ]; then
          echo "COMMITTER_EMAIL and COMMITTER_NAME are required"
          exit 1
        fi
        sudo chown -R $USER:$USER .
        git fetch origin integration/${{ inputs.PROJECT_VERSION }}-translation
        git checkout ${{ inputs.PROJECT_BRANCH }} -f
        git reset --hard origin/${{ inputs.PROJECT_BRANCH }}
        git clean -fdx
        git merge --squash origin/integration/${{ inputs.PROJECT_VERSION }}-translation 2>&1
        git checkout origin/${{ inputs.PROJECT_BRANCH }} -- crowdin.yml
        if git status | grep -q "nothing to commit"; then
          echo "Nothing to commit"
        else
          git commit -m "Merge Translations"
          git push origin
        fi
      env:
        GIT_AUTHOR_NAME: ${{ inputs.CROWDIN_COMMITTER_NAME }}
        GIT_AUTHOR_EMAIL: ${{ inputs.CROWDIN_COMMITTER_EMAIL }}
        GIT_COMMITTER_NAME: ${{ inputs.CROWDIN_COMMITTER_NAME }}
        GIT_COMMITTER_EMAIL: ${{ inputs.CROWDIN_COMMITTER_EMAIL }}
branding:
  icon: "anchor"
  color: "gray-dark"